name: base
channels:
  - conda-forge
dependencies:
  - brotlipy=0.7.0=py39h5161555_1003
  - ca-certificates=2021.10.8=h4653dfc_0
  - certifi=2021.10.8=py39h2804cbe_1
  - cffi=1.15.0=py39h52b1de0_0
  - charset-normalizer=2.0.9=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - conda=4.11.0=py39h2804cbe_0
  - conda-package-handling=1.7.3=py39h5161555_1
  - cryptography=36.0.0=py39hfb8cd70_0
  - idna=3.1=pyhd3deb0d_0
  - libffi=3.4.2=h3422bc3_5
  - libzlib=1.2.11=hee7b306_1013
  - ncurses=6.2=h9aa5885_4
  - openssl=1.1.1l=h3422bc3_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pycosat=0.6.3=py39h5161555_1009
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py39h2804cbe_4
  - python=3.9.7=h54d631c_3_cpython
  - python_abi=3.9=2_cp39
  - readline=8.1=hedafd6a_0
  - requests=2.26.0=pyhd8ed1ab_1
  - ruamel_yaml=0.15.80=py39h5161555_1006
  - setuptools=59.4.0=py39h2804cbe_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h72a2b83_0
  - tk=8.6.11=he1e0b03_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - tzdata=2021e=he74cb21_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h642e427_1
  - yaml=0.2.5=h642e427_0
  - zlib=1.2.11=hee7b306_1013
  - pip:
      - appnope==0.1.2
      - backcall==0.2.0
      - decorator==5.1.0
      - et-xmlfile==1.1.0
      - ipython==7.30.1
      - jedi==0.18.1
      - lxml==4.7.1
      - matplotlib-inline==0.1.3
      - numpy==1.21.5
      - openpyxl==3.0.9
      - pandas==1.3.5
      - pandas-datareader==0.10.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - prompt-toolkit==3.0.24
      - ptyprocess==0.7.0
      - pyglet==1.5.21
      - pygments==2.10.0
      - python-dateutil==2.8.2
      - pytz==2021.3
      - traitlets==5.1.1
      - wcwidth==0.2.5
